/**
 * Icon category definitions for the icon picker.
 *
 * Two formats are supported:
 *   - PascalCase (legacy Lucide): "ZapOff", "Home" – converted to "lucide:zap-off" etc. at runtime
 *   - Iconify ID: "mdi:garage", "lucide:zap" – used as-is
 *
 * Icons that are not found in the loaded icon sets are silently skipped.
 */

export interface IconCategory {
  id: string;
  label: string;
  /** PascalCase Lucide names OR full Iconify IDs (prefix:name) */
  icons: string[];
}

export const ICON_CATEGORIES: IconCategory[] = [
  {
    id: 'arrows',
    label: 'Arrows',
    icons: [
      'ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ArrowUpDown','ArrowLeftRight',
      'ArrowUpRight','ArrowDownLeft','ArrowUpLeft','ArrowDownRight',
      'ArrowBigUp','ArrowBigDown','ArrowBigLeft','ArrowBigRight',
      'ArrowBigUpDash','ArrowBigDownDash','ArrowBigLeftDash','ArrowBigRightDash',
      'ChevronUp','ChevronDown','ChevronLeft','ChevronRight',
      'ChevronsUp','ChevronsDown','ChevronsLeft','ChevronsRight',
      'ChevronsUpDown','ChevronsLeftRight',
      'MoveUp','MoveDown','MoveLeft','MoveRight','Move','MoveHorizontal','MoveVertical',
      'MoveUpRight','MoveDownLeft','MoveUpLeft','MoveDownRight',
      'CornerUpLeft','CornerUpRight','CornerDownLeft','CornerDownRight',
      'RotateCw','RotateCcw','RefreshCw','RefreshCcw','Repeat','Repeat1','Repeat2','Shuffle',
      'TrendingUp','TrendingDown','TrendingUpDown',
      'Undo','Undo2','Redo','Redo2',
      'ArrowDownUp','ArrowRightLeft',
      'ArrowUpFromLine','ArrowDownFromLine','ArrowLeftFromLine','ArrowRightFromLine',
      'ArrowUpToLine','ArrowDownToLine','ArrowLeftToLine','ArrowRightToLine',
      'CircleArrowUp','CircleArrowDown','CircleArrowLeft','CircleArrowRight',
      'SquareArrowUp','SquareArrowDown','SquareArrowLeft','SquareArrowRight',
    ],
  },
  {
    id: 'communication',
    label: 'Communication',
    icons: [
      'Mail','MailOpen','MailCheck','MailX','MailPlus','MailMinus','MailSearch',
      'Inbox','InboxIcon',
      'MessageCircle','MessageSquare','MessageSquareMore','MessageSquarePlus',
      'MessageSquareX','MessageSquareCode','MessageSquareText','MessagesSquare',
      'Phone','PhoneCall','PhoneForwarded','PhoneIncoming','PhoneOff','PhoneOutgoing','PhoneMissed',
      'Bell','BellRing','BellOff','BellDot','BellMinus','BellPlus','BellElectric',
      'Send','SendHorizontal','Reply','ReplyAll','Forward',
      'Megaphone','MegaphoneOff',
      'AtSign','Hash','Rss',
    ],
  },
  {
    id: 'devices',
    label: 'Devices',
    icons: [
      'Monitor','MonitorCheck','MonitorDot','MonitorOff','MonitorSmartphone','MonitorSpeaker',
      'MonitorCog','MonitorDown','MonitorPause','MonitorPlay','MonitorStop','MonitorUp','MonitorX',
      'Laptop','Laptop2','LaptopMinimal',
      'Smartphone','SmartphoneCharging','SmartphoneNfc','SmartphoneCog',
      'Tablet','TabletSmartphone',
      'Tv','Tv2','TvMinimal','TvMinimalPlay',
      'Printer','PrinterCheck',
      'Keyboard','Mouse','Touchpad','TouchpadOff',
      'Gamepad','Gamepad2','Joystick',
      'Headphones','HeadphoneOff','Speaker','SpeakerIcon','Mic','MicOff',
      'Camera','CameraOff','Video','VideoOff','Webcam','WebcamOff',
      'Watch','Server','HardDrive','HardDriveDownload','HardDriveUpload',
      'Cpu','MemoryStick','Bot','CircuitBoard','Usb','Router','Projector',
      'ScanLine','Scan','ScanBarcode','ScanQrCode',
    ],
  },
  {
    id: 'home',
    label: 'Home',
    icons: [
      'Home','Building','Building2',
      'Warehouse','Factory','Hotel','School','School2','Hospital','Church','Castle','Tent',
      'DoorOpen','DoorClosed',
      'Sofa','Bed','BedDouble','BedSingle','Bath','Toilet',
      'Microwave','CookingPot','Refrigerator','WashingMachine',
      'Fence','Mailbox',
      'Lamp','LampDesk','LampFloor','LampWallUp','LampCeiling',
      'Armchair','AirVent','AlarmSmoke','Cctv','Heater',
      'Blinds','BlindsIcon',
      'Lightbulb','LightbulbOff',
      'Plug','Plug2','PlugZap','Switch','PowerOff',
      'Thermometer','Droplets','Flame','Fan',
    ],
  },
  {
    id: 'energy',
    label: 'Energy & Power',
    icons: [
      'Zap','ZapOff',
      'Battery','BatteryCharging','BatteryFull','BatteryLow','BatteryMedium','BatteryWarning',
      'Plug','Plug2','PlugZap','Power','PowerOff','PowerCircle',
      'Gauge','GaugeLow','GaugeHigh',
      'Flame','Droplets','Wind','Sun','SunMedium','SunDim',
      'Thermometer','ThermometerSun','ThermometerSnowflake',
      'Atom','Radiation','Fuel','UtilityPole','SolarPanel','Nuclear','Bolt',
    ],
  },
  {
    id: 'weather',
    label: 'Nature & Weather',
    icons: [
      'Sun','SunDim','SunMedium','SunMoon','SunSnow',
      'Moon','MoonStar',
      'Cloud','CloudRain','CloudSnow','CloudSun','CloudMoon','CloudLightning',
      'CloudDrizzle','CloudHail','CloudFog','CloudMoonRain','CloudSunRain',
      'CloudOff','CloudAlert','CloudCheck','CloudSync',
      'Cloudy','Wind','Snowflake','Droplets',
      'Leaf','TreePine','Tree','Flower','Flower2',
      'Mountain','MountainSnow','Waves','Rainbow','Tornado',
      'Eclipse','Sunrise','Sunset','Umbrella','Thermometer',
    ],
  },
  {
    id: 'security',
    label: 'Security',
    icons: [
      'Lock','LockOpen','LockKeyhole','LockKeyholeOpen',
      'Key','KeyRound','KeySquare',
      'Shield','ShieldCheck','ShieldAlert','ShieldBan','ShieldMinus',
      'ShieldOff','ShieldPlus','ShieldQuestion','ShieldX','ShieldUser','ShieldHalf',
      'Eye','EyeOff','EyeClosed',
      'Fingerprint','Scan','ScanFace','ScanEye',
      'AlertOctagon','AlertTriangle','AlertCircle',
      'Ban','CircleSlash','CircleSlash2',
      'UserRoundX','UserRoundCheck','UserX','UserCheck',
    ],
  },
  {
    id: 'connectivity',
    label: 'Connectivity',
    icons: [
      'Wifi','WifiOff','WifiHigh','WifiLow','WifiZero',
      'Bluetooth','BluetoothConnected','BluetoothOff','BluetoothSearching',
      'Network','Globe','Globe2','GlobeLock','GlobeIcon',
      'Antenna','Signal','SignalHigh','SignalLow','SignalMedium','SignalZero',
      'Nfc','Cast','Share','Share2','Link','Link2','Unlink','Unlink2',
      'Server','Cloud','CloudOff','Satellite','SatelliteDish','RadioTower',
      'Cable',
    ],
  },
  {
    id: 'transport',
    label: 'Transport',
    icons: [
      'Car','CarFront','CarTaxiFront','TruckElectric',
      'Truck','Bike','Bus','BusFront',
      'Train','TrainFront','TrainTrack',
      'Plane','PlaneLanding','PlaneTakeoff',
      'Ship','Sailboat','Anchor','Fuel',
      'Navigation','Navigation2',
      'Rocket','Ambulance','Forklift','Tractor','CableCar','TramFront','Moped',
      'Caravan','Bike',
    ],
  },
  {
    id: 'media',
    label: 'Media & Audio',
    icons: [
      'Play','Pause','Square','Stop',
      'SkipBack','SkipForward','FastForward','Rewind',
      'PlayCircle','PauseCircle','StopCircle',
      'Music','Music2','Music3','Music4',
      'Mic','MicOff','Volume','Volume1','Volume2','VolumeX','VolumeOff',
      'Headphones','Radio','Podcast',
      'Speaker','Film','Clapperboard',
      'Rss','Airplay','Tv','MonitorPlay',
      'Image','Images','Aperture','Camera',
      'ListMusic','AudioLines','AudioWaveform',
      'Youtube','Twitch',
    ],
  },
  {
    id: 'charts',
    label: 'Charts & Data',
    icons: [
      'BarChart','BarChart2','BarChart3','BarChart4',
      'BarChartHorizontal','BarChartHorizontalBig',
      'BarChartBig',
      'LineChart','AreaChart','PieChart','ScatterChart',
      'CandlestickChart',
      'ChartBar','ChartBarBig','ChartBarDecreasing','ChartBarIncreasing','ChartBarStacked',
      'ChartLine','ChartArea','ChartPie','ChartScatter',
      'ChartCandlestick','ChartGantt','ChartNetwork',
      'ChartNoAxesBar','ChartNoAxesColumn','ChartNoAxesCombined',
      'Activity','TrendingUp','TrendingDown','TrendingUpDown',
      'Database','Table','Table2','Grid2x2','Grid3x3',
      'Sigma','Percent','Hash',
    ],
  },
  {
    id: 'time',
    label: 'Time & Calendar',
    icons: [
      'Clock','Clock1','Clock2','Clock3','Clock4','Clock5','Clock6',
      'Clock7','Clock8','Clock9','Clock10','Clock11','Clock12',
      'Timer','TimerOff','TimerReset',
      'AlarmClock','AlarmClockCheck','AlarmClockMinus','AlarmClockOff','AlarmClockPlus',
      'Calendar','CalendarDays','CalendarCheck','CalendarCheck2','CalendarClock',
      'CalendarHeart','CalendarMinus','CalendarOff','CalendarPlus',
      'CalendarRange','CalendarSearch','CalendarX','CalendarX2',
      'CalendarArrowDown','CalendarArrowUp',
      'Hourglass','Watch','Sunrise','Sunset',
    ],
  },
  {
    id: 'tools',
    label: 'Tools & Settings',
    icons: [
      'Settings','Settings2','SlidersHorizontal','SlidersVertical',
      'Wrench','Hammer','Screwdriver','Scissors','Ruler',
      'PenTool','Palette','Pipette','Eraser','Pencil','Pen',
      'Edit','Edit2','Edit3',
      'Trash','Trash2',
      'Copy','Cut','Paste','Clipboard','ClipboardCheck','ClipboardList','ClipboardX','ClipboardPaste',
      'Filter','FilterX',
      'Search','SearchX','SearchCheck','SearchSlash',
      'ZoomIn','ZoomOut',
      'Layers','Layers2','Layers3',
      'Wand','Wand2','Sparkles','Crosshair','Target',
    ],
  },
  {
    id: 'health',
    label: 'Health & Medical',
    icons: [
      'Heart','HeartHandshake','HeartPulse','HeartCrack','HeartOff','HeartPlus',
      'Stethoscope','Pill','Syringe','Bandage','Bandaging',
      'Activity','Brain','Eye','Bone','Dumbbell','Thermometer',
      'Hospital','Ambulance','Cross','Plus',
      'Microscope','FlaskConical','FlaskRound',
      'PersonStanding','Accessibility',
      'Apple','Salad','Utensils',
    ],
  },
  {
    id: 'gaming',
    label: 'Gaming',
    icons: [
      'Gamepad','Gamepad2','Joystick',
      'Sword','Swords','Shield','Trophy','Crown',
      'Target','Crosshair',
      'Dice1','Dice2','Dice3','Dice4','Dice5','Dice6',
      'Puzzle','Ghost','Skull',
      'Zap','Star','Sparkles','Flag',
      'Gem','Coins','Rocket','Wand','Wand2','Scroll',
    ],
  },
  {
    id: 'people',
    label: 'People',
    icons: [
      'User','UserRound','Users','UsersRound',
      'UserCheck','UserRoundCheck','UserCog','UserMinus','UserPlus',
      'UserSearch','UserX','UserRoundMinus','UserRoundPlus','UserRoundX',
      'UserRoundCog',
      'Baby','PersonStanding','Bot',
      'Contact','ContactRound','IdCard',
      'BadgeCheck','BadgeAlert','Badge',
      'Hand','HandMetal','Handshake',
      'Accessibility','GraduationCap','ChefHat','HardHat','Briefcase',
    ],
  },
  {
    id: 'files',
    label: 'Files & Folders',
    icons: [
      'File','FileText','FileImage','FileVideo','FileAudio','FileCode','FileCode2',
      'FileJson','FileJson2','FilePlus','FilePlus2','FileMinus','FileMinus2',
      'FileX','FileX2','FileCheck','FileCheck2','FileSearch','FileSearch2',
      'FileLock','FileLock2','FileKey','FileKey2',
      'Folder','FolderOpen','FolderPlus','FolderMinus','FolderX','FolderClosed',
      'FolderLock','FolderRoot','FolderSearch','FolderTree','FolderDot',
      'Archive','ArchiveRestore','Paperclip','Download','Upload',
    ],
  },
  {
    id: 'status',
    label: 'Status & Alerts',
    icons: [
      'Check','CheckCheck','CheckCircle','CheckCircle2','CheckSquare',
      'X','XCircle','XSquare','XOctagon',
      'AlertCircle','AlertOctagon','AlertTriangle',
      'Info','HelpCircle',
      'Ban','CircleSlash','CircleDashed','CircleDot',
      'Loader','Loader2','LoaderCircle',
      'RefreshCw','RotateCw',
      'Plus','Minus','CirclePlus','CircleMinus','CircleX','CircleCheck',
      'ThumbsUp','ThumbsDown',
      'Flag','FlagOff','Bookmark','BookmarkCheck',
    ],
  },
  {
    id: 'layout',
    label: 'Layout',
    icons: [
      'LayoutDashboard','LayoutGrid','LayoutList','LayoutPanelLeft','LayoutPanelTop','LayoutTemplate',
      'Grid','Grid2x2','Grid3x3',
      'Columns2','Columns3','Columns4',
      'Rows2','Rows3','Rows4',
      'Sidebar','SidebarClose','SidebarOpen',
      'PanelLeft','PanelRight','PanelTop','PanelBottom','PanelLeftClose','PanelRightClose',
      'Maximize','Maximize2','Minimize','Minimize2','Expand','Shrink','Focus',
      'SplitSquareHorizontal','SplitSquareVertical',
    ],
  },
  {
    id: 'text',
    label: 'Text',
    icons: [
      'Type','Text','Heading','Heading1','Heading2','Heading3','Heading4','Heading5','Heading6',
      'Bold','Italic','Underline','Strikethrough',
      'Code','Code2','CodeXml','Terminal',
      'AlignLeft','AlignCenter','AlignRight','AlignJustify',
      'Indent','Outdent',
      'List','ListOrdered','ListChecks','ListTree','ListVideo','ListMusic',
      'Quote','Superscript','Subscript','Pilcrow',
      'Diff','CaseSensitive','CaseUpper','CaseLower',
    ],
  },
  {
    id: 'shapes',
    label: 'Shapes',
    icons: [
      'Circle','Square','Triangle','Pentagon','Hexagon','Octagon','Diamond','Star',
      'CircleDot','SquareDot','Dot','Minus','Plus','X','Check','Slash',
      'Asterisk','Equal','Cylinder','Cone','Cuboid','Box','Package',
      'Heart','Spade','Club','Clover',
    ],
  },
  {
    id: 'social',
    label: 'Social',
    icons: [
      'Share','Share2','Heart','ThumbsUp','ThumbsDown','Star',
      'Bookmark','BookmarkCheck','BookmarkMinus','BookmarkPlus','BookmarkX',
      'Globe','Link','AtSign','Hash','MessageCircle',
      'Users','UserPlus','UserCheck','Send','Reply','Forward',
      'Megaphone','Rss','QrCode','Handshake',
    ],
  },
  {
    id: 'food',
    label: 'Food & Beverage',
    icons: [
      'Coffee','Tea','Wine','WineOff','Beer','BeerOff','Cocktail',
      'Pizza','Sandwich','Salad','Soup','Egg','EggFried',
      'Milk','MilkOff','Cake','CakeSlice','Candy','CandyOff',
      'Apple','Banana','Grape','Carrot',
      'Croissant','Cookie','IceCreamBowl','IceCreamCone','Lollipop',
      'Beef','Fish','Ham','Shrimp',
      'Popcorn','Noodles','CookingPot','Utensils','UtensilsCrossed',
      'Microwave','Refrigerator',
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    icons: [
      'Anchor','Award','Backpack','Badge','Bell','Book','BookOpen','BookMarked',
      'Briefcase','Calendar','Camera','Car','Chair','Compass',
      'Crown','Cup','Diamond','Dumbbell','Feather','Flashlight','Football',
      'Gem','Gift','GiftIcon','Globe','Glasses','GraduationCap',
      'HandHelping','Headset','Home','Hourglass',
      'Key','Leaf','Lightbulb','Magnet','Map','Medal',
      'Palette','Paperclip','Pen','Phone','Piano','Pill','Pin',
      'PiggyBank','Printer','Rocket','Ruler','Scissors','Shield',
      'ShoppingBag','ShoppingCart','Sofa','Star','Sword','Tag',
      'Tent','Ticket','Timer','Tool','Torch','Trophy','Tv','Umbrella',
      'Watch','Wrench','Zap',
    ],
  },

  // ── MDI (Material Design Icons) ──────────────────────────────────────────────
  {
    id: 'mdi-home',
    label: 'MDI – Gebäude & Räume',
    icons: [
      'mdi:home','mdi:home-outline','mdi:home-variant','mdi:home-variant-outline',
      'mdi:garage','mdi:garage-open','mdi:garage-variant','mdi:garage-open-variant',
      'mdi:garage-alert','mdi:garage-lock',
      'mdi:door','mdi:door-open','mdi:door-closed','mdi:door-closed-lock',
      'mdi:window-closed','mdi:window-open','mdi:window-closed-variant','mdi:window-open-variant',
      'mdi:gate','mdi:gate-open','mdi:gate-arrow-left','mdi:gate-arrow-right',
      'mdi:fence','mdi:fence-electric',
      'mdi:shed','mdi:barn',
      'mdi:office-building','mdi:office-building-outline',
      'mdi:apartment','mdi:castle','mdi:warehouse',
      'mdi:floor-plan','mdi:home-floor-0','mdi:home-floor-1','mdi:home-floor-2','mdi:home-floor-3',
      'mdi:stairs','mdi:elevator','mdi:elevator-up','mdi:elevator-down',
      'mdi:pillar','mdi:wall','mdi:fence-outline',
    ],
  },
  {
    id: 'mdi-energy',
    label: 'MDI – Energie & Heizung',
    icons: [
      'mdi:solar-panel','mdi:solar-panel-large','mdi:solar-power','mdi:solar-power-variant',
      'mdi:wind-turbine','mdi:transmission-tower','mdi:power-plug','mdi:power-plug-outline',
      'mdi:power-plug-off','mdi:power-socket','mdi:power-socket-eu','mdi:power-socket-de',
      'mdi:lightning-bolt','mdi:lightning-bolt-circle',
      'mdi:meter-electric','mdi:meter-gas','mdi:meter-water',
      'mdi:radiator','mdi:radiator-off','mdi:radiator-disabled',
      'mdi:heat-pump','mdi:heat-pump-outline',
      'mdi:fireplace','mdi:fireplace-off',
      'mdi:air-conditioner','mdi:hvac','mdi:hvac-off',
      'mdi:oil-burner','mdi:gas-burner',
      'mdi:thermometer','mdi:thermometer-high','mdi:thermometer-low','mdi:thermometer-lines',
      'mdi:water-boiler','mdi:water-boiler-off','mdi:water-heater',
      'mdi:pipe','mdi:pipe-valve','mdi:pipe-wrench',
      'mdi:ev-station','mdi:ev-plug-type1','mdi:ev-plug-type2','mdi:ev-plug-ccs1','mdi:ev-plug-ccs2',
      'mdi:battery','mdi:battery-charging','mdi:battery-high','mdi:battery-medium','mdi:battery-low',
      'mdi:battery-alert','mdi:home-battery','mdi:home-battery-outline',
    ],
  },
  {
    id: 'mdi-automation',
    label: 'MDI – Smart Home',
    icons: [
      'mdi:home-automation','mdi:home-assistant',
      'mdi:robot','mdi:robot-outline',
      'mdi:vacuum','mdi:vacuum-outline','mdi:robot-vacuum','mdi:robot-vacuum-variant',
      'mdi:washing-machine','mdi:dishwasher','mdi:tumble-dryer','mdi:fridge','mdi:microwave',
      'mdi:coffee-maker','mdi:kettle','mdi:toaster-oven',
      'mdi:air-purifier','mdi:air-humidifier','mdi:air-dehumidifier',
      'mdi:fan','mdi:fan-off','mdi:fan-speed-1','mdi:fan-speed-2','mdi:fan-speed-3',
      'mdi:lightbulb','mdi:lightbulb-outline','mdi:lightbulb-off','mdi:lightbulb-off-outline',
      'mdi:lightbulb-on','mdi:lightbulb-on-outline','mdi:lightbulb-group','mdi:lightbulb-multiple',
      'mdi:lamp','mdi:floor-lamp','mdi:ceiling-light','mdi:wall-sconce','mdi:string-lights',
      'mdi:led-strip','mdi:led-strip-variant',
      'mdi:blinds','mdi:blinds-open','mdi:roller-shade','mdi:roller-shade-closed',
      'mdi:curtains','mdi:curtains-closed',
      'mdi:toggle-switch','mdi:toggle-switch-off','mdi:toggle-switch-variant','mdi:toggle-switch-off-outline',
      'mdi:remote','mdi:remote-tv','mdi:television','mdi:television-box',
      'mdi:speaker','mdi:speaker-multiple','mdi:speaker-wireless','mdi:volume-high','mdi:volume-off',
    ],
  },
  {
    id: 'mdi-security',
    label: 'MDI – Sicherheit',
    icons: [
      'mdi:lock','mdi:lock-open','mdi:lock-outline','mdi:lock-open-outline',
      'mdi:lock-smart','mdi:lock-plus','mdi:lock-reset',
      'mdi:key','mdi:key-variant','mdi:key-chain','mdi:key-wireless',
      'mdi:shield','mdi:shield-home','mdi:shield-check','mdi:shield-alert','mdi:shield-lock',
      'mdi:alarm','mdi:alarm-light','mdi:alarm-bell','mdi:alarm-check',
      'mdi:bell','mdi:bell-ring','mdi:bell-off','mdi:doorbell','mdi:doorbell-video',
      'mdi:motion-sensor','mdi:motion-sensor-off',
      'mdi:smoke-detector','mdi:smoke-detector-variant','mdi:smoke-detector-alert',
      'mdi:leak','mdi:water-alert','mdi:water-check',
      'mdi:cctv','mdi:camera','mdi:camera-outline','mdi:camera-wireless','mdi:camera-wireless-outline',
      'mdi:eye','mdi:eye-off','mdi:eye-outline',
      'mdi:fingerprint','mdi:face-recognition',
    ],
  },
  {
    id: 'mdi-sensors',
    label: 'MDI – Sensoren',
    icons: [
      'mdi:thermometer','mdi:thermometer-lines','mdi:thermometer-probe',
      'mdi:humidity','mdi:water-percent',
      'mdi:gauge','mdi:gauge-low','mdi:gauge-full','mdi:gauge-empty',
      'mdi:speedometer','mdi:speedometer-slow','mdi:speedometer-medium',
      'mdi:weather-windy','mdi:weather-sunny','mdi:weather-cloudy','mdi:weather-rainy',
      'mdi:weather-snowy','mdi:weather-fog','mdi:weather-lightning','mdi:weather-partly-cloudy',
      'mdi:brightness-5','mdi:brightness-6','mdi:brightness-7','mdi:brightness-auto',
      'mdi:co2','mdi:molecule-co2','mdi:air-filter',
      'mdi:ruler','mdi:ruler-square','mdi:tape-measure',
      'mdi:weight','mdi:scale','mdi:scale-balance',
      'mdi:pulse','mdi:heart-pulse','mdi:blood-bag',
      'mdi:vibrate','mdi:vibration',
      'mdi:signal','mdi:signal-variant','mdi:wifi','mdi:wifi-off',
      'mdi:battery-bluetooth','mdi:bluetooth','mdi:bluetooth-off',
    ],
  },
  {
    id: 'mdi-transport',
    label: 'MDI – Fahrzeuge & Verkehr',
    icons: [
      'mdi:car','mdi:car-outline','mdi:car-side','mdi:car-back','mdi:car-estate',
      'mdi:car-sports','mdi:car-convertible','mdi:car-limousine','mdi:car-pickup',
      'mdi:car-electric','mdi:car-electric-outline','mdi:car-wireless',
      'mdi:car-key','mdi:car-door','mdi:car-door-lock',
      'mdi:car-battery','mdi:car-tire-alert',
      'mdi:truck','mdi:truck-outline','mdi:truck-delivery','mdi:van-utility',
      'mdi:bus','mdi:train','mdi:ferry','mdi:airplane','mdi:helicopter',
      'mdi:bike','mdi:motorbike','mdi:scooter','mdi:walk','mdi:run',
      'mdi:parking','mdi:parking-outline','mdi:road','mdi:traffic-light',
    ],
  },
  {
    id: 'mdi-nature',
    label: 'MDI – Natur & Garten',
    icons: [
      'mdi:tree','mdi:tree-outline','mdi:forest','mdi:pine-tree','mdi:cactus',
      'mdi:flower','mdi:flower-outline','mdi:flower-tulip','mdi:flower-pollen',
      'mdi:leaf','mdi:leaf-maple','mdi:sprout','mdi:grass',
      'mdi:watering-can','mdi:watering-can-outline',
      'mdi:irrigation','mdi:sprinkler','mdi:sprinkler-variant','mdi:sprinkler-fire',
      'mdi:shovel','mdi:rake','mdi:lawnmower','mdi:robot-mower',
      'mdi:sun-thermometer','mdi:sun-snowflake',
      'mdi:pool','mdi:hot-tub','mdi:sauna',
      'mdi:bee','mdi:bug','mdi:ladybug',
      'mdi:cat','mdi:dog','mdi:fish','mdi:rabbit','mdi:cow',
    ],
  },
];
