/**
 * Lucide icon category definitions for the icon picker.
 * Icon names are PascalCase matching lucide-react's exported component names.
 * Icons that don't exist in the installed version are simply ignored.
 */

export interface IconCategory {
  id: string;
  label: string;
  /** PascalCase names – names not found in lucide-react are silently skipped */
  icons: string[];
}

export const ICON_CATEGORIES: IconCategory[] = [
  {
    id: 'arrows',
    label: 'Arrows',
    icons: [
      'ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ArrowUpDown','ArrowLeftRight',
      'ArrowUpRight','ArrowDownLeft','ArrowUpLeft','ArrowDownRight',
      'ArrowBigUp','ArrowBigDown','ArrowBigLeft','ArrowBigRight',
      'ArrowBigUpDash','ArrowBigDownDash','ArrowBigLeftDash','ArrowBigRightDash',
      'ChevronUp','ChevronDown','ChevronLeft','ChevronRight',
      'ChevronsUp','ChevronsDown','ChevronsLeft','ChevronsRight',
      'ChevronsUpDown','ChevronsLeftRight',
      'MoveUp','MoveDown','MoveLeft','MoveRight','Move','MoveHorizontal','MoveVertical',
      'MoveUpRight','MoveDownLeft','MoveUpLeft','MoveDownRight',
      'CornerUpLeft','CornerUpRight','CornerDownLeft','CornerDownRight',
      'RotateCw','RotateCcw','RefreshCw','RefreshCcw','Repeat','Repeat1','Repeat2','Shuffle',
      'TrendingUp','TrendingDown','TrendingUpDown',
      'Undo','Undo2','Redo','Redo2',
      'ArrowDownUp','ArrowRightLeft',
      'ArrowUpFromLine','ArrowDownFromLine','ArrowLeftFromLine','ArrowRightFromLine',
      'ArrowUpToLine','ArrowDownToLine','ArrowLeftToLine','ArrowRightToLine',
      'CircleArrowUp','CircleArrowDown','CircleArrowLeft','CircleArrowRight',
      'SquareArrowUp','SquareArrowDown','SquareArrowLeft','SquareArrowRight',
    ],
  },
  {
    id: 'communication',
    label: 'Communication',
    icons: [
      'Mail','MailOpen','MailCheck','MailX','MailPlus','MailMinus','MailSearch',
      'Inbox','InboxIcon',
      'MessageCircle','MessageSquare','MessageSquareMore','MessageSquarePlus',
      'MessageSquareX','MessageSquareCode','MessageSquareText','MessagesSquare',
      'Phone','PhoneCall','PhoneForwarded','PhoneIncoming','PhoneOff','PhoneOutgoing','PhoneMissed',
      'Bell','BellRing','BellOff','BellDot','BellMinus','BellPlus','BellElectric',
      'Send','SendHorizontal','Reply','ReplyAll','Forward',
      'Megaphone','MegaphoneOff',
      'AtSign','Hash','Rss',
    ],
  },
  {
    id: 'devices',
    label: 'Devices',
    icons: [
      'Monitor','MonitorCheck','MonitorDot','MonitorOff','MonitorSmartphone','MonitorSpeaker',
      'MonitorCog','MonitorDown','MonitorPause','MonitorPlay','MonitorStop','MonitorUp','MonitorX',
      'Laptop','Laptop2','LaptopMinimal',
      'Smartphone','SmartphoneCharging','SmartphoneNfc','SmartphoneCog',
      'Tablet','TabletSmartphone',
      'Tv','Tv2','TvMinimal','TvMinimalPlay',
      'Printer','PrinterCheck',
      'Keyboard','Mouse','Touchpad','TouchpadOff',
      'Gamepad','Gamepad2','Joystick',
      'Headphones','HeadphoneOff','Speaker','SpeakerIcon','Mic','MicOff',
      'Camera','CameraOff','Video','VideoOff','Webcam','WebcamOff',
      'Watch','Server','HardDrive','HardDriveDownload','HardDriveUpload',
      'Cpu','MemoryStick','Bot','CircuitBoard','Usb','Router','Projector',
      'ScanLine','Scan','ScanBarcode','ScanQrCode',
    ],
  },
  {
    id: 'home',
    label: 'Home',
    icons: [
      'Home','Building','Building2',
      'Warehouse','Factory','Hotel','School','School2','Hospital','Church','Castle','Tent',
      'DoorOpen','DoorClosed',
      'Sofa','Bed','BedDouble','BedSingle','Bath','Toilet',
      'Microwave','CookingPot','Refrigerator','WashingMachine',
      'Fence','Mailbox',
      'Lamp','LampDesk','LampFloor','LampWallUp','LampCeiling',
      'Armchair','AirVent','AlarmSmoke','Cctv','Heater',
      'Blinds','BlindsIcon',
      'Lightbulb','LightbulbOff',
      'Plug','Plug2','PlugZap','Switch','PowerOff',
      'Thermometer','Droplets','Flame','Fan',
    ],
  },
  {
    id: 'energy',
    label: 'Energy & Power',
    icons: [
      'Zap','ZapOff',
      'Battery','BatteryCharging','BatteryFull','BatteryLow','BatteryMedium','BatteryWarning',
      'Plug','Plug2','PlugZap','Power','PowerOff','PowerCircle',
      'Gauge','GaugeLow','GaugeHigh',
      'Flame','Droplets','Wind','Sun','SunMedium','SunDim',
      'Thermometer','ThermometerSun','ThermometerSnowflake',
      'Atom','Radiation','Fuel','UtilityPole','SolarPanel','Nuclear','Bolt',
    ],
  },
  {
    id: 'weather',
    label: 'Nature & Weather',
    icons: [
      'Sun','SunDim','SunMedium','SunMoon','SunSnow',
      'Moon','MoonStar',
      'Cloud','CloudRain','CloudSnow','CloudSun','CloudMoon','CloudLightning',
      'CloudDrizzle','CloudHail','CloudFog','CloudMoonRain','CloudSunRain',
      'CloudOff','CloudAlert','CloudCheck','CloudSync',
      'Cloudy','Wind','Snowflake','Droplets',
      'Leaf','TreePine','Tree','Flower','Flower2',
      'Mountain','MountainSnow','Waves','Rainbow','Tornado',
      'Eclipse','Sunrise','Sunset','Umbrella','Thermometer',
    ],
  },
  {
    id: 'security',
    label: 'Security',
    icons: [
      'Lock','LockOpen','LockKeyhole','LockKeyholeOpen',
      'Key','KeyRound','KeySquare',
      'Shield','ShieldCheck','ShieldAlert','ShieldBan','ShieldMinus',
      'ShieldOff','ShieldPlus','ShieldQuestion','ShieldX','ShieldUser','ShieldHalf',
      'Eye','EyeOff','EyeClosed',
      'Fingerprint','Scan','ScanFace','ScanEye',
      'AlertOctagon','AlertTriangle','AlertCircle',
      'Ban','CircleSlash','CircleSlash2',
      'UserRoundX','UserRoundCheck','UserX','UserCheck',
    ],
  },
  {
    id: 'connectivity',
    label: 'Connectivity',
    icons: [
      'Wifi','WifiOff','WifiHigh','WifiLow','WifiZero',
      'Bluetooth','BluetoothConnected','BluetoothOff','BluetoothSearching',
      'Network','Globe','Globe2','GlobeLock','GlobeIcon',
      'Antenna','Signal','SignalHigh','SignalLow','SignalMedium','SignalZero',
      'Nfc','Cast','Share','Share2','Link','Link2','Unlink','Unlink2',
      'Server','Cloud','CloudOff','Satellite','SatelliteDish','RadioTower',
      'Cable',
    ],
  },
  {
    id: 'transport',
    label: 'Transport',
    icons: [
      'Car','CarFront','CarTaxiFront','TruckElectric',
      'Truck','Bike','Bus','BusFront',
      'Train','TrainFront','TrainTrack',
      'Plane','PlaneLanding','PlaneTakeoff',
      'Ship','Sailboat','Anchor','Fuel',
      'Navigation','Navigation2',
      'Rocket','Ambulance','Forklift','Tractor','CableCar','TramFront','Moped',
      'Caravan','Bike',
    ],
  },
  {
    id: 'media',
    label: 'Media & Audio',
    icons: [
      'Play','Pause','Square','Stop',
      'SkipBack','SkipForward','FastForward','Rewind',
      'PlayCircle','PauseCircle','StopCircle',
      'Music','Music2','Music3','Music4',
      'Mic','MicOff','Volume','Volume1','Volume2','VolumeX','VolumeOff',
      'Headphones','Radio','Podcast',
      'Speaker','Film','Clapperboard',
      'Rss','Airplay','Tv','MonitorPlay',
      'Image','Images','Aperture','Camera',
      'ListMusic','AudioLines','AudioWaveform',
      'Youtube','Twitch',
    ],
  },
  {
    id: 'charts',
    label: 'Charts & Data',
    icons: [
      'BarChart','BarChart2','BarChart3','BarChart4',
      'BarChartHorizontal','BarChartHorizontalBig',
      'BarChartBig',
      'LineChart','AreaChart','PieChart','ScatterChart',
      'CandlestickChart',
      'ChartBar','ChartBarBig','ChartBarDecreasing','ChartBarIncreasing','ChartBarStacked',
      'ChartLine','ChartArea','ChartPie','ChartScatter',
      'ChartCandlestick','ChartGantt','ChartNetwork',
      'ChartNoAxesBar','ChartNoAxesColumn','ChartNoAxesCombined',
      'Activity','TrendingUp','TrendingDown','TrendingUpDown',
      'Database','Table','Table2','Grid2x2','Grid3x3',
      'Sigma','Percent','Hash',
    ],
  },
  {
    id: 'time',
    label: 'Time & Calendar',
    icons: [
      'Clock','Clock1','Clock2','Clock3','Clock4','Clock5','Clock6',
      'Clock7','Clock8','Clock9','Clock10','Clock11','Clock12',
      'Timer','TimerOff','TimerReset',
      'AlarmClock','AlarmClockCheck','AlarmClockMinus','AlarmClockOff','AlarmClockPlus',
      'Calendar','CalendarDays','CalendarCheck','CalendarCheck2','CalendarClock',
      'CalendarHeart','CalendarMinus','CalendarOff','CalendarPlus',
      'CalendarRange','CalendarSearch','CalendarX','CalendarX2',
      'CalendarArrowDown','CalendarArrowUp',
      'Hourglass','Watch','Sunrise','Sunset',
    ],
  },
  {
    id: 'tools',
    label: 'Tools & Settings',
    icons: [
      'Settings','Settings2','SlidersHorizontal','SlidersVertical',
      'Wrench','Hammer','Screwdriver','Scissors','Ruler',
      'PenTool','Palette','Pipette','Eraser','Pencil','Pen',
      'Edit','Edit2','Edit3',
      'Trash','Trash2',
      'Copy','Cut','Paste','Clipboard','ClipboardCheck','ClipboardList','ClipboardX','ClipboardPaste',
      'Filter','FilterX',
      'Search','SearchX','SearchCheck','SearchSlash',
      'ZoomIn','ZoomOut',
      'Layers','Layers2','Layers3',
      'Wand','Wand2','Sparkles','Crosshair','Target',
    ],
  },
  {
    id: 'health',
    label: 'Health & Medical',
    icons: [
      'Heart','HeartHandshake','HeartPulse','HeartCrack','HeartOff','HeartPlus',
      'Stethoscope','Pill','Syringe','Bandage','Bandaging',
      'Activity','Brain','Eye','Bone','Dumbbell','Thermometer',
      'Hospital','Ambulance','Cross','Plus',
      'Microscope','FlaskConical','FlaskRound',
      'PersonStanding','Accessibility',
      'Apple','Salad','Utensils',
    ],
  },
  {
    id: 'gaming',
    label: 'Gaming',
    icons: [
      'Gamepad','Gamepad2','Joystick',
      'Sword','Swords','Shield','Trophy','Crown',
      'Target','Crosshair',
      'Dice1','Dice2','Dice3','Dice4','Dice5','Dice6',
      'Puzzle','Ghost','Skull',
      'Zap','Star','Sparkles','Flag',
      'Gem','Coins','Rocket','Wand','Wand2','Scroll',
    ],
  },
  {
    id: 'people',
    label: 'People',
    icons: [
      'User','UserRound','Users','UsersRound',
      'UserCheck','UserRoundCheck','UserCog','UserMinus','UserPlus',
      'UserSearch','UserX','UserRoundMinus','UserRoundPlus','UserRoundX',
      'UserRoundCog',
      'Baby','PersonStanding','Bot',
      'Contact','ContactRound','IdCard',
      'BadgeCheck','BadgeAlert','Badge',
      'Hand','HandMetal','Handshake',
      'Accessibility','GraduationCap','ChefHat','HardHat','Briefcase',
    ],
  },
  {
    id: 'files',
    label: 'Files & Folders',
    icons: [
      'File','FileText','FileImage','FileVideo','FileAudio','FileCode','FileCode2',
      'FileJson','FileJson2','FilePlus','FilePlus2','FileMinus','FileMinus2',
      'FileX','FileX2','FileCheck','FileCheck2','FileSearch','FileSearch2',
      'FileLock','FileLock2','FileKey','FileKey2',
      'Folder','FolderOpen','FolderPlus','FolderMinus','FolderX','FolderClosed',
      'FolderLock','FolderRoot','FolderSearch','FolderTree','FolderDot',
      'Archive','ArchiveRestore','Paperclip','Download','Upload',
    ],
  },
  {
    id: 'status',
    label: 'Status & Alerts',
    icons: [
      'Check','CheckCheck','CheckCircle','CheckCircle2','CheckSquare',
      'X','XCircle','XSquare','XOctagon',
      'AlertCircle','AlertOctagon','AlertTriangle',
      'Info','HelpCircle',
      'Ban','CircleSlash','CircleDashed','CircleDot',
      'Loader','Loader2','LoaderCircle',
      'RefreshCw','RotateCw',
      'Plus','Minus','CirclePlus','CircleMinus','CircleX','CircleCheck',
      'ThumbsUp','ThumbsDown',
      'Flag','FlagOff','Bookmark','BookmarkCheck',
    ],
  },
  {
    id: 'layout',
    label: 'Layout',
    icons: [
      'LayoutDashboard','LayoutGrid','LayoutList','LayoutPanelLeft','LayoutPanelTop','LayoutTemplate',
      'Grid','Grid2x2','Grid3x3',
      'Columns2','Columns3','Columns4',
      'Rows2','Rows3','Rows4',
      'Sidebar','SidebarClose','SidebarOpen',
      'PanelLeft','PanelRight','PanelTop','PanelBottom','PanelLeftClose','PanelRightClose',
      'Maximize','Maximize2','Minimize','Minimize2','Expand','Shrink','Focus',
      'SplitSquareHorizontal','SplitSquareVertical',
    ],
  },
  {
    id: 'text',
    label: 'Text',
    icons: [
      'Type','Text','Heading','Heading1','Heading2','Heading3','Heading4','Heading5','Heading6',
      'Bold','Italic','Underline','Strikethrough',
      'Code','Code2','CodeXml','Terminal',
      'AlignLeft','AlignCenter','AlignRight','AlignJustify',
      'Indent','Outdent',
      'List','ListOrdered','ListChecks','ListTree','ListVideo','ListMusic',
      'Quote','Superscript','Subscript','Pilcrow',
      'Diff','CaseSensitive','CaseUpper','CaseLower',
    ],
  },
  {
    id: 'shapes',
    label: 'Shapes',
    icons: [
      'Circle','Square','Triangle','Pentagon','Hexagon','Octagon','Diamond','Star',
      'CircleDot','SquareDot','Dot','Minus','Plus','X','Check','Slash',
      'Asterisk','Equal','Cylinder','Cone','Cuboid','Box','Package',
      'Heart','Spade','Club','Clover',
    ],
  },
  {
    id: 'social',
    label: 'Social',
    icons: [
      'Share','Share2','Heart','ThumbsUp','ThumbsDown','Star',
      'Bookmark','BookmarkCheck','BookmarkMinus','BookmarkPlus','BookmarkX',
      'Globe','Link','AtSign','Hash','MessageCircle',
      'Users','UserPlus','UserCheck','Send','Reply','Forward',
      'Megaphone','Rss','QrCode','Handshake',
    ],
  },
  {
    id: 'food',
    label: 'Food & Beverage',
    icons: [
      'Coffee','Tea','Wine','WineOff','Beer','BeerOff','Cocktail',
      'Pizza','Sandwich','Salad','Soup','Egg','EggFried',
      'Milk','MilkOff','Cake','CakeSlice','Candy','CandyOff',
      'Apple','Banana','Grape','Carrot',
      'Croissant','Cookie','IceCreamBowl','IceCreamCone','Lollipop',
      'Beef','Fish','Ham','Shrimp',
      'Popcorn','Noodles','CookingPot','Utensils','UtensilsCrossed',
      'Microwave','Refrigerator',
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    icons: [
      'Anchor','Award','Backpack','Badge','Bell','Book','BookOpen','BookMarked',
      'Briefcase','Calendar','Camera','Car','Chair','Compass',
      'Crown','Cup','Diamond','Dumbbell','Feather','Flashlight','Football',
      'Gem','Gift','GiftIcon','Globe','Glasses','GraduationCap',
      'HandHelping','Headset','Home','Hourglass',
      'Key','Leaf','Lightbulb','Magnet','Map','Medal',
      'Palette','Paperclip','Pen','Phone','Piano','Pill','Pin',
      'PiggyBank','Printer','Rocket','Ruler','Scissors','Shield',
      'ShoppingBag','ShoppingCart','Sofa','Star','Sword','Tag',
      'Tent','Ticket','Timer','Tool','Torch','Trophy','Tv','Umbrella',
      'Watch','Wrench','Zap',
    ],
  },
];
