#!/usr/bin/env node
/**
 * Publishes the MCP recipes as JSON, so the editor's AI prompt can use the same
 * worked examples the MCP server hands out.
 *
 *   node tools/schema/gen-recipes.mjs          write public/ai/aura-recipes.json
 *   node tools/schema/gen-recipes.mjs --check  fail if the file is out of date
 *
 * One source, two consumers: lib/mcp/recipes.js is CommonJS adapter code and the
 * frontend is an ESM bundle, so the data travels as JSON rather than as a second
 * hand-maintained copy that would drift the first time a recipe is fixed.
 */

import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const OUT_FILE = path.join(ROOT, 'public/ai/aura-recipes.json');

const { RECIPES } = require(path.join(ROOT, 'lib/mcp/recipes.js'));
const { version } = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));

const payload = {
    $meta: {
        auraVersion: version,
        source: 'lib/mcp/recipes.js — generated by tools/schema/gen-recipes.mjs, do not edit',
    },
    recipes: RECIPES.map(({ id, title, when, instead, notes, widgets }) => ({
        id,
        title,
        when,
        instead,
        notes,
        widgets,
    })),
};

const json = `${JSON.stringify(payload, null, 2)}\n`;
const current = fs.existsSync(OUT_FILE) ? fs.readFileSync(OUT_FILE, 'utf8') : '';

if (process.argv.includes('--check')) {
    if (current !== json) {
        console.error('public/ai/aura-recipes.json is out of date — run: npm run recipes');
        process.exit(1);
    }
    console.log(`public/ai/aura-recipes.json: up to date (${payload.recipes.length} recipes)`);
} else {
    fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
    fs.writeFileSync(OUT_FILE, json);
    console.log(`public/ai/aura-recipes.json: ${payload.recipes.length} recipes`);
}
