// Per-widget metadata for the documentation generator.
// `slug` → docs/widgets/<slug>.md + assets/<slug>/. `hint` is the registry
// description. `runtime` describes how to render a runtime screenshot from
// mocked data (null = config-dialog only, for widgets that need real adapter
// data to render meaningfully). `group` mirrors the registry widgetGroup.
//
// switch (schalter) and timer (zeitschaltuhr) are already documented by hand.

export const GROUPS = [
    { id: 'control', label: 'Steuerung & Anzeige' },
    { id: 'special', label: 'Spezial' },
    { id: 'layout', label: 'Layout' },
];

// r(val, opts?, extra?) → runtime descriptor; null → config dialog only.
const r = (val, options = {}, extra = {}) => ({ val, options, ...extra });

export const WIDGETS = [
    // ── Steuerung & Anzeige ──────────────────────────────────────────────────
    { type: 'shutter', slug: 'rollladen', label: 'Rollladen', group: 'control',
      hint: 'Rollladen-Position (0–100 %) steuern und anzeigen.',
      runtime: r(45, {}, { w: 9, h: 6 }) },
    { type: 'dimmer', slug: 'dimmer', label: 'Dimmer', group: 'control',
      hint: 'Licht dimmen – Helligkeitsregler 0–100 % mit Ein/Aus-Taste.',
      runtime: r(75, {}, { w: 11, h: 6 }) },
    { type: 'slider', slug: 'schieberegler', label: 'Schieberegler', group: 'control',
      hint: 'Beliebigen Zahlenwert per Schieberegler einstellen.',
      runtime: r(50, { unit: '%', min: 0, max: 100 }, { w: 11, h: 5 }) },
    { type: 'thermostat', slug: 'thermostat', label: 'Thermostat', group: 'control',
      hint: 'Soll-Temperatur einstellen und Ist-Temperatur anzeigen.',
      runtime: r(21, {}, { w: 11, h: 7 }) },
    { type: 'value', slug: 'wert-anzeige', label: 'Wert-Anzeige', group: 'control',
      hint: 'Einen Datenpunktwert als Zahl/Text anzeigen (read-only).',
      runtime: r(21.5, { unit: '°C' }, { w: 11, h: 5 }) },
    { type: 'gauge', slug: 'gauge', label: 'Gauge', group: 'control',
      hint: 'Zahlenwert als Tachonadel/Kreisbogen visualisieren.',
      runtime: r(72, { unit: 'kW', min: 0, max: 100 }, { w: 11, h: 8 }) },
    { type: 'fill', slug: 'fuellstandsanzeige', label: 'Füllstandsanzeige', group: 'control',
      hint: 'Füllstand (z. B. Wassertank, Heizöl) als Balken visualisieren.',
      runtime: r(68, { unit: '%' }, { w: 9, h: 9 }) },
    { type: 'knob', slug: 'drehregler', label: 'Drehregler', group: 'control',
      hint: 'Wert über Drehknopf einstellen – 3 Zeigertypen, Winkelbereich konfigurierbar.',
      runtime: r(65, { unit: '%' }, { w: 8, h: 8 }) },
    { type: 'windowcontact', slug: 'fensterkontakt', label: 'Fenster-/Türkontakt', group: 'control',
      hint: 'Fenster- oder Türkontakt-Status anzeigen (offen/geschlossen).',
      runtime: r(false, {}, { w: 11, h: 5 }) },
    { type: 'binarysensor', slug: 'binaersensor', label: 'Binärsensor', group: 'control',
      hint: 'Allgemeinen Binärsensor anzeigen (z. B. Bewegungsmelder, Alarm).',
      runtime: r(true, {}, { w: 11, h: 5 }) },
    { type: 'climate', slug: 'raumklima', label: 'Raumklima', group: 'control',
      hint: 'Temperatur, Luftfeuchtigkeit und optionalen Temperaturverlauf kombiniert anzeigen.',
      runtime: r(21.4, {}, { w: 12, h: 7 }) },
    { type: 'datepicker', slug: 'datumswaehler', label: 'Datumswähler', group: 'control',
      hint: 'Datum/Uhrzeit auswählen und als Datenpunkt speichern.',
      runtime: r('2025-06-17', {}, { w: 11, h: 5 }) },
    { type: 'input', slug: 'eingabefeld', label: 'Eingabefeld', group: 'control',
      hint: 'Text per Tastatur eingeben und in einen Datenpunkt schreiben.',
      runtime: r('Wohnzimmer', {}, { w: 12, h: 4 }) },
    { type: 'enum', slug: 'auswahlfeld', label: 'Auswahlfeld', group: 'control',
      hint: 'DP-Werte (0,1,2…) auf Text-Labels mappen; Dropdown schreibt den Wert zurück.',
      runtime: null },
    { type: 'chart', slug: 'diagramm', label: 'Diagramm (einfach)', group: 'control',
      hint: 'Verlauf eines einzelnen Datenpunkts als einfaches Diagramm.', runtime: null },
    { type: 'echart', slug: 'diagramm-erweitert', label: 'Diagramm (erweitert)', group: 'control',
      hint: 'Erweitertes Diagramm mit mehreren Datenpunkten und Optionen.', runtime: null },
    { type: 'echartsPreset', slug: 'echarts', label: 'eCharts', group: 'control',
      hint: 'Vorkonfiguriertes eCharts-Diagramm per JSON-Preset.', runtime: null },
    { type: 'light', slug: 'rgb-licht', label: 'RGB-Licht', group: 'control',
      hint: 'RGB / CCT / Dimmer in einem Widget – Helligkeit, Farbe, Lichtwärme, Effekte.', runtime: null },
    { type: 'mediaplayer', slug: 'mediaplayer', label: 'Mediaplayer', group: 'control',
      hint: 'Mediaplayer steuern (Sonos, Squeezeserver, Spotify …).', runtime: null },
    { type: 'list', slug: 'liste', label: 'Statische Liste', group: 'control',
      hint: 'Manuell gepflegte Liste mit frei konfigurierbaren Datenpunkt-Links.', runtime: null },
    { type: 'autolist', slug: 'dynamische-liste', label: 'Dynamische Liste', group: 'control',
      hint: 'Datenpunkte automatisch aus einem ioBroker-Ordner auflisten.', runtime: null },
    { type: 'chips', slug: 'chips', label: 'Schnellzugriff-Chips', group: 'control',
      hint: 'Kompakte Schaltflächen-Leiste für Szenen und häufige Aktionen.', runtime: null },
    { type: 'httpRequest', slug: 'http-aktion', label: 'HTTP-Aktion', group: 'control',
      hint: 'HTTP GET/POST-Anfrage per Klick auslösen (z. B. Webhook).', runtime: null },
    { type: 'universal', slug: 'universal-widget', label: 'Universal-Widget', group: 'control',
      hint: 'Freies Raster – Zellen einzeln mit Schaltern, Reglern, Werten und Bildern belegen.', runtime: null },

    // ── Spezial ───────────────────────────────────────────────────────────────
    { type: 'clock', slug: 'uhrzeit', label: 'Uhrzeit', group: 'special',
      hint: 'Aktuelle Uhrzeit und Datum anzeigen (kein Datenpunkt nötig).',
      runtime: r(null, {}, { w: 11, h: 6, noDp: true }) },
    { type: 'weather', slug: 'wetter', label: 'Wetter', group: 'special',
      hint: 'Wetterdaten vom ioBroker-Wetter-Adapter anzeigen.', runtime: null },
    { type: 'calendar', slug: 'kalender', label: 'Kalender', group: 'special',
      hint: 'Termine aus dem iCal-Adapter (nur per Tab-Wizard hinzufügbar).', runtime: null },
    { type: 'evcc', slug: 'evcc', label: 'evcc', group: 'special',
      hint: 'evcc Wallbox-Ladesteuerung einbinden.', runtime: null },
    { type: 'camera', slug: 'kamera', label: 'Kamera', group: 'special',
      hint: 'Kamera-Livebild einbinden (go2rtc / MJPEG-Stream).', runtime: null },
    { type: 'image', slug: 'bild', label: 'Bild', group: 'special',
      hint: 'Statisches Bild, lokale Datei oder URL anzeigen.', runtime: null },
    { type: 'trash', slug: 'muellabfuhr', label: 'Müllabfuhr', group: 'special',
      hint: 'Nächste Müllabfuhr-Termine vom Trash-Adapter anzeigen.', runtime: null },
    { type: 'trashSchedule', slug: 'muellabfuhr-zeitplan', label: 'Müllabfuhr-Zeitplan', group: 'special',
      hint: 'Detaillierter Müllabfuhr-Kalender (Datenpunkt vom Trash-Adapter).', runtime: null },
    { type: 'jsontable', slug: 'json-tabelle', label: 'JSON-Tabelle', group: 'special',
      hint: 'JSON-Array-Datenpunkt als formatierte Tabelle anzeigen.',
      runtime: r(JSON.stringify([
          { Raum: 'Wohnzimmer', Temperatur: '21.5 °C', Status: 'OK' },
          { Raum: 'Küche', Temperatur: '23.1 °C', Status: 'OK' },
          { Raum: 'Bad', Temperatur: '24.0 °C', Status: 'OK' },
      ]), {}, { w: 13, h: 6 }) },
    { type: 'iframe', slug: 'iframe', label: 'iFrame', group: 'special',
      hint: 'Externe Webseite oder lokale URL einbetten.', runtime: null },
    { type: 'html', slug: 'html', label: 'HTML', group: 'special',
      hint: 'Beliebigen HTML/CSS-Code frei einbetten.', runtime: null },
    { type: 'stateimage', slug: 'zustandsbild', label: 'Zustandsbild', group: 'special',
      hint: 'Je nach Zustand (true/false) ein anderes Bild anzeigen.', runtime: null },
    { type: 'adapterstatus', slug: 'adapter-status', label: 'Adapter-Status', group: 'special',
      hint: 'Liste aller ioBroker-Instanzen mit Status, Update-Hinweisen und Aktionen.', runtime: null },
    { type: 'scriptstatus', slug: 'skript-status', label: 'Skript-Status', group: 'special',
      hint: 'Liste aller JavaScript-Skripte mit Status, Filter und Start-/Stopp-Aktionen.', runtime: null },
    { type: 'adapterlogs', slug: 'adapter-logs', label: 'Adapter-Logs', group: 'special',
      hint: 'Live-Log-Stream aller Adapter — Filter nach Schweregrad, Adapter und Freitext.', runtime: null },
    { type: 'alarm', slug: 'alarmanlage', label: 'Alarmanlage', group: 'special',
      hint: 'ioBroker.alarm-Adapter steuern — Scharf/Inside/Nacht, Zonen, PIN, Tages-Log.', runtime: null },
    { type: 'map', slug: 'karte', label: 'Karte', group: 'special',
      hint: 'Positionen (Auto, Kind, …) aus Datenpunkten auf einer OpenStreetMap-Karte anzeigen – optional mit Entfernung.', runtime: null },
    { type: 'carousel', slug: 'karussell', label: 'Karussell', group: 'special',
      hint: 'Horizontal scrollbare Chip-Liste – pro Item Datenpunkt + eigene Klick-Aktion.', runtime: null },

    // ── Layout ──────────────────────────────────────────────────────────────
    { type: 'header', slug: 'abschnittstitel', label: 'Abschnittstitel', group: 'layout',
      hint: 'Trennlinie mit Überschrift zur Gliederung des Dashboards.',
      runtime: r(null, { title: 'Wohnzimmer' }, { w: 14, h: 2, noDp: true, title: 'Wohnzimmer' }) },
    { type: 'button', slug: 'button', label: 'Button', group: 'layout',
      hint: 'Klick-Aktion auslösen (Datenpunkt schreiben, HTTP-Call, Szene …).',
      runtime: r(null, {}, { w: 6, h: 4, noDp: true, title: 'Szene starten' }) },
    { type: 'group', slug: 'gruppe', label: 'Gruppe', group: 'layout',
      hint: 'Mehrere Widgets in einem gemeinsamen Rahmen gruppieren.', runtime: null },
    { type: 'panels', slug: 'panels', label: 'Panels', group: 'layout',
      hint: 'Mehrere Widgets als swipebare Slides – Wischen, Pagination-Dots und Pfeil-Buttons.', runtime: null },
];
