// Per-widget metadata for the documentation generator.
// `slug` → docs/widgets/<slug>.md + assets/<slug>/. `hint` is the registry
// description. `runtime` describes how to render a runtime screenshot from
// mocked data (null = config-dialog only, for widgets that need real adapter
// data to render meaningfully). `group` mirrors the registry widgetGroup.
//
// switch (schalter) and timer (zeitschaltuhr) are already documented by hand.

export const GROUPS = [
    { id: 'control', label: 'Steuerung & Anzeige' },
    { id: 'special', label: 'Spezial' },
    { id: 'layout', label: 'Layout' },
];

// r(val, opts?, extra?) → runtime descriptor; null → config dialog only.
const r = (val, options = {}, extra = {}) => ({ val, options, ...extra });

export const WIDGETS = [
    // ── Steuerung & Anzeige ──────────────────────────────────────────────────
    { type: 'shutter', slug: 'rollladen', label: 'Rollladen', group: 'control',
      hint: 'Rollladen-Position (0–100 %) steuern und anzeigen.',
      runtime: r(45, {}, { w: 9, h: 6 }) },
    { type: 'dimmer', slug: 'dimmer', label: 'Dimmer', group: 'control',
      hint: 'Licht dimmen – Helligkeitsregler 0–100 % mit Ein/Aus-Taste.',
      runtime: r(75, {}, { w: 11, h: 6 }) },
    { type: 'slider', slug: 'schieberegler', label: 'Schieberegler', group: 'control',
      hint: 'Beliebigen Zahlenwert per Schieberegler einstellen.',
      runtime: r(50, { unit: '%', min: 0, max: 100 }, { w: 11, h: 5 }) },
    { type: 'thermostat', slug: 'thermostat', label: 'Thermostat', group: 'control',
      hint: 'Soll-Temperatur einstellen und Ist-Temperatur anzeigen.',
      layouts: ['default', 'compact', 'minimal', 'dial', 'custom'],
      // Pilot for per-layout/variant shots (see plan). Actual temp (19.5) sits
      // below the 21 °C setpoint → heating state (flame + red accent) is visible.
      runtime: r(21, { actualDatapoint: 'demo.thermostat.actual' }, { w: 11, h: 7,
        mock: { 'demo.thermostat.actual': 19.5 } }),
      shots: [
        { file: 'layout-default', layout: 'default', w: 11, h: 7,
          options: { actualDatapoint: 'demo.thermostat.actual' }, mock: { 'demo.thermostat.actual': 19.5 } },
        { file: 'layout-compact', layout: 'compact', w: 18, h: 3,
          options: { actualDatapoint: 'demo.thermostat.actual' }, mock: { 'demo.thermostat.actual': 19.5 } },
        { file: 'layout-minimal', layout: 'minimal', w: 8, h: 9,
          options: { actualDatapoint: 'demo.thermostat.actual' }, mock: { 'demo.thermostat.actual': 19.5 } },
        { file: 'layout-dial', layout: 'dial', w: 9, h: 12,
          options: { actualDatapoint: 'demo.thermostat.actual', showPresets: false, minTemp: 10, maxTemp: 30 },
          mock: { 'demo.thermostat.actual': 19.5 } },
        { file: 'layout-custom', layout: 'custom', w: 15, h: 6,
          options: {
            actualDatapoint: 'demo.thermostat.actual',
            customGrid: {
              cols: 3, rows: 2, colSizes: ['auto', '1fr', 'auto'],
              cells: [
                { type: 'component', componentKey: 'icon', align: 'center', valign: 'middle' },
                { type: 'title', align: 'left', valign: 'middle', bold: true },
                { type: 'component', componentKey: 'btn-plus', align: 'center', valign: 'middle' },
                { type: 'field', fieldKey: 'actual', align: 'left', valign: 'middle', color: 'var(--text-secondary)' },
                { type: 'value', suffix: '°C', align: 'left', valign: 'middle', bold: true, fontSize: 22, color: 'var(--accent-red)' },
                { type: 'component', componentKey: 'btn-minus', align: 'center', valign: 'middle' },
              ],
            },
          },
          mock: { 'demo.thermostat.actual': 19.5 } },
        // Markante Config-Variante: Schwellwert-Färbung der Ist-Temperatur.
        { file: 'variant-schwellwerte', layout: 'default', w: 11, h: 7,
          options: { actualDatapoint: 'demo.thermostat.actual', colorThresholds: [[20, 'var(--accent)'], [30, 'var(--accent-red)']] },
          mock: { 'demo.thermostat.actual': 19.5 } },
        // Farbschwellen der Rundskala – hier greift das dritte Band (Soll 21 °C).
        { file: 'variant-dial-schwellen', layout: 'dial', w: 9, h: 12,
          options: { actualDatapoint: 'demo.thermostat.actual', showPresets: false, minTemp: 10, maxTemp: 30,
            dialColorThresholds: [[19, '#3b82f6'], [22, '#f59e0b'], [30, '#ef4444']] },
          mock: { 'demo.thermostat.actual': 19.5 } },
      ] },
    { type: 'value', slug: 'wert-anzeige', label: 'Wert-Anzeige', group: 'control',
      hint: 'Einen Datenpunktwert als Zahl/Text anzeigen (read-only).',
      runtime: r(21.5, { unit: '°C' }, { w: 11, h: 5 }) },
    { type: 'gauge', slug: 'gauge', label: 'Gauge', group: 'control',
      hint: 'Zahlenwert als Tachonadel/Kreisbogen visualisieren.',
      runtime: r(72, { unit: 'kW', minValue: 0, maxValue: 100 }, { w: 11, h: 8 }) },
    { type: 'fill', slug: 'fuellstandsanzeige', label: 'Füllstandsanzeige', group: 'control',
      hint: 'Füllstand (z. B. Wassertank, Heizöl) als Balken visualisieren, mit verstellbaren Grenzen.',
      layouts: ['default', 'battery', 'bar', 'segments', 'wave'],
      runtime: r(68, { unit: '%' }, { w: 9, h: 9 }) },
    { type: 'knob', slug: 'drehregler', label: 'Drehregler', group: 'control',
      hint: 'Wert über Drehknopf einstellen – 3 Zeigertypen, Winkelbereich konfigurierbar.',
      runtime: r(65, { unit: '%' }, { w: 8, h: 8 }) },
    { type: 'windowcontact', slug: 'fensterkontakt', label: 'Fenster-/Türkontakt', group: 'control',
      hint: 'Fenster- oder Türkontakt-Status anzeigen (offen/geschlossen).',
      runtime: r(false, {}, { w: 11, h: 5 }) },
    { type: 'binarysensor', slug: 'binaersensor', label: 'Binärsensor', group: 'control',
      hint: 'Allgemeinen Binärsensor anzeigen (z. B. Bewegungsmelder, Alarm).',
      runtime: r(true, {}, { w: 11, h: 5 }) },
    { type: 'climate', slug: 'raumklima', label: 'Raumklima', group: 'control',
      hint: 'Temperatur, Luftfeuchtigkeit und optionalen Temperaturverlauf kombiniert anzeigen.',
      runtime: r(21.4, {}, { w: 12, h: 7 }) },
    { type: 'datepicker', slug: 'datumswaehler', label: 'Datumswähler', group: 'control',
      hint: 'Datum/Uhrzeit auswählen und als Datenpunkt speichern.',
      runtime: r('2025-06-17', {}, { w: 11, h: 5 }) },
    { type: 'input', slug: 'eingabefeld', label: 'Eingabefeld', group: 'control',
      hint: 'Text per Tastatur eingeben und in einen Datenpunkt schreiben.',
      runtime: r('Wohnzimmer', {}, { w: 12, h: 4 }) },
    { type: 'enum', slug: 'auswahlfeld', label: 'Auswahlfeld', group: 'control',
      hint: 'DP-Werte (0,1,2…) auf Text-Labels mappen; Dropdown schreibt den Wert zurück.',
      runtime: null },
    { type: 'chart', slug: 'diagramm', label: 'Diagramm (einfach)', group: 'control',
      hint: 'Verlauf eines einzelnen Datenpunkts als einfaches Diagramm.', runtime: null },
    { type: 'echart', slug: 'diagramm-erweitert', label: 'Diagramm (erweitert)', group: 'control',
      hint: 'Erweitertes Diagramm mit mehreren Datenpunkten und Optionen.', runtime: null },
    { type: 'energiebilanz', slug: 'verteilung', label: 'Diagramm (Verteilung)', group: 'control',
      hint: 'Anteilige Darstellung (Balken, Torte oder Donut) beliebig vieler Gruppen aus mehreren Datenpunkten mit History-Aggregation – z.B. Energiebilanz, Kosten, Speicherbelegung',
      // Documented by hand (docs/widgets/verteilung.md); its images come from
      // tools/screenshots/verteilung-examples.mjs, not from widgets-all.mjs — hence the
      // explicit grid + screenshot paths instead of runtime.png / config.png.
      runtime: null, defaultGrid: { w: 8, h: 8 },
      hero: 'assets/verteilung/bsp-vt-bilanz.png',
      configShot: 'assets/verteilung/bsp-vt-config.png' },
    { type: 'echartsPreset', slug: 'echarts', label: 'eCharts', group: 'control',
      hint: 'Vorkonfiguriertes eCharts-Diagramm per JSON-Preset.', runtime: null },
    { type: 'light', slug: 'rgb-licht', label: 'RGB-Licht', group: 'control',
      hint: 'RGB / CCT / Dimmer in einem Widget – Helligkeit, Farbe, Lichtwärme, Effekte.', runtime: null },
    { type: 'mediaplayer', slug: 'mediaplayer', label: 'Mediaplayer', group: 'control',
      hint: 'Mediaplayer steuern (Sonos, Squeezeserver, Spotify …).', runtime: null },
    { type: 'list', slug: 'liste', label: 'Statische Liste', group: 'control',
      hint: 'Manuell gepflegte Liste mit frei konfigurierbaren Datenpunkt-Links.', runtime: null },
    { type: 'autolist', slug: 'dynamische-liste', label: 'Dynamische Liste', group: 'control',
      hint: 'Datenpunkte automatisch aus einem ioBroker-Ordner auflisten.', runtime: null },
    { type: 'chips', slug: 'chips', label: 'Schnellzugriff-Chips', group: 'control',
      hint: 'Kompakte Schaltflächen-Leiste für Szenen und häufige Aktionen.', runtime: null },
    { type: 'httpRequest', slug: 'http-aktion', label: 'HTTP-Aktion', group: 'control',
      hint: 'HTTP GET/POST-Anfrage per Klick auslösen (z. B. Webhook).', runtime: null },
    { type: 'universal', slug: 'universal-widget', label: 'Universal-Widget', group: 'control',
      hint: 'Freies Raster – Zellen einzeln mit Schaltern, Reglern, Werten und Bildern belegen.', runtime: null },

    // ── Spezial ───────────────────────────────────────────────────────────────
    { type: 'clock', slug: 'uhrzeit', label: 'Uhrzeit', group: 'special',
      hint: 'Aktuelle Uhrzeit und Datum anzeigen (kein Datenpunkt nötig).',
      runtime: r(null, {}, { w: 11, h: 6, noDp: true }) },
    { type: 'weather', slug: 'wetter', label: 'Wetter', group: 'special',
      hint: 'Wetterdaten vom ioBroker-Wetter-Adapter anzeigen.', runtime: null },
    { type: 'calendar', slug: 'kalender', label: 'Kalender', group: 'special',
      hint: 'Termine aus dem iCal-Adapter.', runtime: null },
    { type: 'evcc', slug: 'evcc', label: 'evcc', group: 'special',
      hint: 'evcc Wallbox-Ladesteuerung einbinden.', runtime: null },
    { type: 'camera', slug: 'kamera', label: 'Kamera', group: 'special',
      hint: 'Kamera-Livebild einbinden (go2rtc / MJPEG-Stream).', runtime: null },
    { type: 'image', slug: 'bild', label: 'Bild', group: 'special',
      hint: 'Statisches Bild, lokale Datei oder URL anzeigen.', runtime: null },
    { type: 'trash', slug: 'muellabfuhr', label: 'Müllabfuhr', group: 'special',
      hint: 'Nächste Müllabfuhr-Termine vom Trash-Adapter anzeigen.', runtime: null },
    { type: 'trashSchedule', slug: 'muellabfuhr-zeitplan', label: 'Müllabfuhr-Zeitplan', group: 'special',
      hint: 'Detaillierter Müllabfuhr-Kalender (Datenpunkt vom Trash-Adapter).', runtime: null },
    { type: 'jsontable', slug: 'json-tabelle', label: 'JSON-Tabelle', group: 'special',
      hint: 'JSON-Array-Datenpunkt als formatierte Tabelle anzeigen.',
      runtime: r(JSON.stringify([
          { Raum: 'Wohnzimmer', Temperatur: '21.5 °C', Status: 'OK' },
          { Raum: 'Küche', Temperatur: '23.1 °C', Status: 'OK' },
          { Raum: 'Bad', Temperatur: '24.0 °C', Status: 'OK' },
      ]), {}, { w: 13, h: 6 }) },
    { type: 'iframe', slug: 'iframe', label: 'iFrame', group: 'special',
      hint: 'Externe Webseite oder lokale URL einbetten.', runtime: null },
    { type: 'html', slug: 'html', label: 'HTML', group: 'special',
      hint: 'Beliebigen HTML/CSS-Code frei einbetten.', runtime: null },
    { type: 'stateimage', slug: 'zustandsbild', label: 'Zustandsbild', group: 'special',
      hint: 'Je nach Zustand (true/false) ein anderes Bild anzeigen.', runtime: null },
    { type: 'adapterstatus', slug: 'adapter-status', label: 'Adapter-Status', group: 'special',
      hint: 'Liste aller ioBroker-Instanzen mit Status, Update-Hinweisen und Aktionen.', runtime: null },
    { type: 'scriptstatus', slug: 'skript-status', label: 'Skript-Status', group: 'special',
      hint: 'Liste aller JavaScript-Skripte mit Status, Filter und Start-/Stopp-Aktionen.', runtime: null },
    { type: 'adapterlogs', slug: 'adapter-logs', label: 'Adapter-Logs', group: 'special',
      hint: 'Live-Log-Stream aller Adapter — Filter nach Schweregrad, Adapter und Freitext.', runtime: null },
    { type: 'messages', slug: 'meldungen', label: 'Meldungen', group: 'special',
      layouts: ['default', 'count'],
      hint: 'Verlauf der eingegangenen Informationen, Warnungen und Fehler — Filter nach Schweregrad und Zeitraum.', runtime: null },
    { type: 'alarm', slug: 'alarmanlage', label: 'Alarmanlage', group: 'special',
      hint: 'ioBroker.alarm-Adapter steuern — Scharf/Inside/Nacht, Zonen, PIN, Tages-Log.', runtime: null },
    { type: 'map', slug: 'karte', label: 'Karte', group: 'special',
      hint: 'Positionen (Auto, Kind, …) aus Datenpunkten auf einer OpenStreetMap-Karte anzeigen – optional mit Entfernung.', runtime: null },
    { type: 'carousel', slug: 'karussell', label: 'Karussell', group: 'special',
      hint: 'Horizontal scrollbare Chip-Liste – pro Item Datenpunkt + eigene Klick-Aktion.', runtime: null },

    // ── Layout ──────────────────────────────────────────────────────────────
    { type: 'header', slug: 'abschnittstitel', label: 'Abschnittstitel', group: 'layout',
      hint: 'Trennlinie mit Überschrift zur Gliederung des Dashboards.',
      layouts: ['default', 'compact', 'minimal', 'framed'],
      runtime: r(null, {}, { w: 14, h: 2, noDp: true, title: 'Wohnzimmer' }) },
    { type: 'button', slug: 'button', label: 'Button', group: 'layout',
      hint: 'Klick-Aktion auslösen (Datenpunkt schreiben, HTTP-Call, Szene …).',
      runtime: r(null, {}, { w: 6, h: 4, noDp: true, title: 'Szene starten' }) },
    { type: 'group', slug: 'gruppe', label: 'Gruppe', group: 'layout',
      hint: 'Mehrere Widgets in einem gemeinsamen Rahmen gruppieren.', runtime: null },
    { type: 'panels', slug: 'panels', label: 'Panels', group: 'layout',
      hint: 'Mehrere Widgets als swipebare Slides – Wischen, Pagination-Dots und Pfeil-Buttons.', runtime: null },
    // Menü and Spiegel are documented by hand and their images come from
    // tools/screenshots/menu-mirror.mjs (a menu needs the sections/tabs around it, a
    // mirror a source widget next to it — more than widgets-all.mjs can seed).
    // `customShots` keeps widgets-all.mjs from overwriting those files.
    { type: 'menu', slug: 'menue', label: 'Menü', group: 'layout',
      hint: 'Frei positionierbares Navigations-Menü – zeigt die Bereiche oder die Tabs zum direkten Umschalten.',
      runtime: null, customShots: true, defaultGrid: { w: 12, h: 2 },
      hero: 'assets/menue/variant-hbar.png',
      configShot: 'assets/menue/config.png' },
    { type: 'mirror', slug: 'spiegel', label: 'Spiegel', group: 'layout',
      hint: 'Zeigt ein vorhandenes Widget live an einer zweiten Stelle an – kein Duplikat: Änderungen an der Quelle wirken sofort mit.',
      runtime: null, customShots: true, defaultGrid: { w: 8, h: 4 },
      hero: 'assets/spiegel/runtime.png',
      configShot: 'assets/spiegel/config.png' },
];
